
/*NEWSLETTER SUBSCRIPTION*/
export const SUBSCRIBE_NEWSLETTER = 'zadatak/App/SUBSCRIBE_NEWSLETTER';
export const SUBSCRIBE_NEWSLETTER_SUCCESS = 'zadatak/App/SUBSCRIBE_NEWSLETTER_SUCCESS';
export const SUBSCRIBE_NEWSLETTER_ERROR = 'zadatak/App/SUBSCRIBE_NEWSLETTER_ERROR';


export const DEFAULT_LOCALE = 'en';
